import { id, IDL, query, update } from 'azle';
import { DealStatus, ShippingDetails } from './interfaces/shipment';
import {
  ITransportType,
  MilestoneApprovalStatus,
  MilestoneStatus,
} from './interfaces/global';

export default class {
  @query([], IDL.Text)
  getVersion(): string {
    return '0.0.1';
  }

  @query([IDL.Text], ShippingDetails)
  getShipmentDetails(id: string): ShippingDetails {
    return {
      id,
      name: 'Shipment 2',
      status: DealStatus.Proposal,
      contractId: '124',
      origin: 'Origin 2',
      destination: 'Destination 2',
      presentation: 'Presentation 2',
      variety: 'Variety 2',
      docs: [],
      portOfDestination: 'Port 3',
      portOfOrigin: 'Port 4',
      proposalSupplierEmail: 'supplier2@example.com',
      buyerCompany: {
        name: 'Buyer Company 2',
        country: 'Country 3',
        taxId: 'TaxID3',
      },
      supplierCompany: {
        name: 'Supplier Company 2',
        country: 'Country 4',
        taxId: 'TaxID4',
      },
      proposalBuyerEmail: 'buyer2@example.com',
      shippingStartDate: '2023-10-05',
      expectedShippingEndDate: '2023-10-20',
      currentMilestone: 4,
      suppliers: [
        {
          approved: true,
          email: 'supplier2@example.com',
          id: 'supplier2',
          new: false,
        },
      ],
      buyers: [
        {
          approved: true,
          email: 'buyer2@example.com',
          id: 'buyer2',
          new: false,
        },
      ],
      milestones: [
        {
          description: 'Milestone 1',
          fundsDistribution: 60,
          approvalStatus: MilestoneApprovalStatus.Approved,
          status: MilestoneStatus.COMPLETED,
          docs: [],
          id: '',
        },
        {
          description: 'Milestone 2',
          fundsDistribution: 60,
          approvalStatus: MilestoneApprovalStatus.Approved,
          status: MilestoneStatus.COMPLETED,
          docs: [],
          id: '',
        },
        {
          description: 'Milestone 3',
          fundsDistribution: 60,
          approvalStatus: MilestoneApprovalStatus.Pending,
          status: MilestoneStatus.IN_PROGRESS,
          docs: [],
          id: '',
        },
        {
          description: 'Milestone 4',
          fundsDistribution: 60,
          approvalStatus: MilestoneApprovalStatus.Pending,
          status: MilestoneStatus.IN_PROGRESS,
          docs: [],
          id: '',
        },
        {
          description: 'Milestone 5',
          fundsDistribution: 60,
          approvalStatus: MilestoneApprovalStatus.Pending,
          status: MilestoneStatus.IN_PROGRESS,
          docs: [],
          id: '',
        },
        {
          description: 'Milestone 6',
          fundsDistribution: 60,
          approvalStatus: MilestoneApprovalStatus.Pending,
          status: MilestoneStatus.IN_PROGRESS,
          docs: [],
          id: '',
        },
      ],
      investmentAmount: 2000,
      revenue: 2500,
      netBalance: 500,
      roi: 25,
      duration: '15 days',
      daysLeft: 12,
      quality: 'Medium',
      offerUnitPrice: 200,
      quantity: 10,
      totalValue: 2000,
      transport: ITransportType.BY_SEA,
      description: 'Description 2',
      buyerConfirmed: false,
      supplierConfirmed: true,
      newDocuments: true,
      newForBuyer: true,
      nftID: 2,
      mintTxHash: '0x124',
    };
  }

  @query([], IDL.Vec(ShippingDetails))
  getShipmentsList(): ShippingDetails[] {
    return [
      {
        id: '2',
        name: 'Shipment 2',
        status: DealStatus.Proposal,
        contractId: '124',
        origin: 'Origin 2',
        destination: 'Destination 2',
        presentation: 'Presentation 2',
        variety: 'Variety 2',
        docs: [],
        portOfDestination: 'Port 3',
        portOfOrigin: 'Port 4',
        proposalSupplierEmail: 'supplier2@example.com',
        buyerCompany: {
          name: 'Buyer Company 2',
          country: 'Country 3',
          taxId: 'TaxID3',
        },
        supplierCompany: {
          name: 'Supplier Company 2',
          country: 'Country 4',
          taxId: 'TaxID4',
        },
        proposalBuyerEmail: 'buyer2@example.com',
        shippingStartDate: '2023-10-05',
        expectedShippingEndDate: '2023-10-20',
        currentMilestone: 2,
        suppliers: [
          {
            approved: true,
            email: 'supplier2@example.com',
            id: 'supplier2',
            new: false,
          },
        ],
        buyers: [
          {
            approved: true,
            email: 'buyer2@example.com',
            id: 'buyer2',
            new: false,
          },
        ],
        milestones: [
          {
            description: 'Milestone 2',
            fundsDistribution: 60,
            approvalStatus: MilestoneApprovalStatus.Pending,
            status: MilestoneStatus.IN_PROGRESS,
            docs: [],
            id: '',
          },
        ],
        investmentAmount: 2000,
        revenue: 2500,
        netBalance: 500,
        roi: 25,
        duration: '15 days',
        daysLeft: 12,
        quality: 'Medium',
        offerUnitPrice: 200,
        quantity: 10,
        totalValue: 2000,
        transport: ITransportType.BY_SEA,
        description: 'Description 2',
        buyerConfirmed: false,
        supplierConfirmed: true,
        newDocuments: true,
        newForBuyer: true,
        nftID: 2,
        mintTxHash: '0x124',
      },
      {
        id: '3',
        name: 'Shipment 3',
        status: DealStatus.Cancelled,
        contractId: '125',
        origin: 'Origin 3',
        destination: 'Destination 3',
        presentation: 'Presentation 3',
        variety: 'Variety 3',
        docs: [],
        portOfDestination: 'Port 5',
        portOfOrigin: 'Port 6',
        proposalSupplierEmail: 'supplier3@example.com',
        buyerCompany: {
          name: 'Buyer Company 3',
          country: 'Country 5',
          taxId: 'TaxID5',
        },
        supplierCompany: {
          name: 'Supplier Company 3',
          country: 'Country 6',
          taxId: 'TaxID6',
        },
        proposalBuyerEmail: 'buyer3@example.com',
        shippingStartDate: '2023-10-10',
        expectedShippingEndDate: '2023-10-25',
        currentMilestone: 3,
        suppliers: [
          {
            approved: true,
            email: 'supplier3@example.com',
            id: 'supplier3',
            new: false,
          },
        ],
        buyers: [
          {
            approved: true,
            email: 'buyer3@example.com',
            id: 'buyer3',
            new: false,
          },
        ],
        milestones: [
          {
            description: 'Milestone 3',
            fundsDistribution: 70,
            approvalStatus: MilestoneApprovalStatus.Approved,
            status: MilestoneStatus.COMPLETED,
            docs: [],
            id: '',
          },
        ],
        investmentAmount: 3000,
        revenue: 3500,
        netBalance: 500,
        roi: 16.67,
        duration: '15 days',
        daysLeft: 5,
        quality: 'Low',
        offerUnitPrice: 300,
        quantity: 10,
        totalValue: 3000,
        transport: ITransportType.BY_SEA,
        description: 'Description 3',
        buyerConfirmed: true,
        supplierConfirmed: false,
        newDocuments: false,
        newForBuyer: false,
        nftID: 3,
        mintTxHash: '0x125',
      },
      {
        id: '4',
        name: 'Shipment 4',
        status: DealStatus.Finished,
        contractId: '126',
        origin: 'Origin 4',
        destination: 'Destination 4',
        presentation: 'Presentation 4',
        variety: 'Variety 4',
        docs: [],
        portOfDestination: 'Port 7',
        portOfOrigin: 'Port 8',
        proposalSupplierEmail: 'supplier4@example.com',
        buyerCompany: {
          name: 'Buyer Company 4',
          country: 'Country 7',
          taxId: 'TaxID7',
        },
        supplierCompany: {
          name: 'Supplier Company 4',
          country: 'Country 8',
          taxId: 'TaxID8',
        },
        proposalBuyerEmail: 'buyer4@example.com',
        shippingStartDate: '2023-10-15',
        expectedShippingEndDate: '2023-10-30',
        currentMilestone: 4,
        suppliers: [
          {
            approved: true,
            email: 'supplier4@example.com',
            id: 'supplier4',
            new: false,
          },
        ],
        buyers: [
          {
            approved: true,
            email: 'buyer4@example.com',
            id: 'buyer4',
            new: false,
          },
        ],
        milestones: [
          {
            description: 'Milestone 4',
            fundsDistribution: 80,
            approvalStatus: MilestoneApprovalStatus.Pending,
            status: MilestoneStatus.IN_PROGRESS,
            docs: [],
            id: '',
          },
        ],
        investmentAmount: 4000,
        revenue: 4500,
        netBalance: 500,
        roi: 12.5,
        duration: '15 days',
        daysLeft: 0,
        quality: 'High',
        offerUnitPrice: 400,
        quantity: 10,
        totalValue: 4000,
        transport: ITransportType.BY_AIR,
        description: 'Description 4',
        buyerConfirmed: true,
        supplierConfirmed: true,
        newDocuments: true,
        newForBuyer: true,
        nftID: 4,
        mintTxHash: '0x126',
      },
      {
        id: '5',
        name: 'Shipment 5',
        status: DealStatus.Cancelled,
        contractId: '127',
        origin: 'Origin 5',
        destination: 'Destination 5',
        presentation: 'Presentation 5',
        variety: 'Variety 5',
        docs: [],
        portOfDestination: 'Port 9',
        portOfOrigin: 'Port 10',
        proposalSupplierEmail: 'supplier5@example.com',
        buyerCompany: {
          name: 'Buyer Company 5',
          country: 'Country 9',
          taxId: 'TaxID9',
        },
        supplierCompany: {
          name: 'Supplier Company 5',
          country: 'Country 10',
          taxId: 'TaxID10',
        },
        proposalBuyerEmail: 'buyer5@example.com',
        shippingStartDate: '2023-10-20',
        expectedShippingEndDate: '2023-11-05',
        currentMilestone: 5,
        suppliers: [
          {
            approved: true,
            email: 'supplier5@example.com',
            id: 'supplier5',
            new: false,
          },
        ],
        buyers: [
          {
            approved: true,
            email: 'buyer5@example.com',
            id: 'buyer5',
            new: false,
          },
        ],
        milestones: [
          {
            description: 'Milestone 5',
            fundsDistribution: 90,
            approvalStatus: MilestoneApprovalStatus.Denied,
            status: MilestoneStatus.COMPLETED,
            docs: [],
            id: '',
          },
        ],
        investmentAmount: 5000,
        revenue: 0,
        netBalance: -5000,
        roi: -100,
        duration: '16 days',
        daysLeft: 16,
        quality: 'Low',
        offerUnitPrice: 500,
        quantity: 10,
        totalValue: 5000,
        transport: ITransportType.BY_SEA,
        description: 'Description 5',
        buyerConfirmed: false,
        supplierConfirmed: false,
        newDocuments: false,
        newForBuyer: false,
        nftID: 5,
        mintTxHash: '0x127',
      },
      {
        id: '1',
        name: 'Shipment 1',
        status: DealStatus.Confirmed,
        contractId: '123',
        origin: 'Origin 1',
        destination: 'Destination 1',
        presentation: 'Presentation 1',
        variety: 'Variety 1',
        docs: [],
        portOfDestination: 'Port 1',
        portOfOrigin: 'Port 2',
        proposalSupplierEmail: 'supplier@example.com',
        buyerCompany: {
          name: 'Buyer Company 1',
          country: 'Country 1',
          taxId: 'TaxID1',
        },
        supplierCompany: {
          name: 'Supplier Company 1',
          country: 'Country 2',
          taxId: 'TaxID2',
        },
        proposalBuyerEmail: 'buyer@example.com',
        shippingStartDate: '2023-10-01',
        expectedShippingEndDate: '2023-10-15',
        currentMilestone: 1,
        suppliers: [
          {
            approved: true,
            email: 'supplier1@example.com',
            id: 'supplier1',
            new: false,
          },
        ],
        buyers: [
          {
            approved: true,
            email: 'buyer1@example.com',
            id: 'buyer1',
            new: false,
          },
        ],
        milestones: [
          {
            description: 'Milestone 1',
            fundsDistribution: 50,
            approvalStatus: MilestoneApprovalStatus.Approved,
            status: MilestoneStatus.COMPLETED,
            docs: [],
            id: '',
          },
        ],
        investmentAmount: 1000,
        revenue: 1500,
        netBalance: 500,
        roi: 50,
        duration: '14 days',
        daysLeft: 10,
        quality: 'High',
        offerUnitPrice: 100,
        quantity: 10,
        totalValue: 1000,
        transport: ITransportType.BY_AIR,
        description: 'Description 1',
        buyerConfirmed: true,
        supplierConfirmed: true,
        newDocuments: false,
        newForBuyer: false,
        nftID: 1,
        mintTxHash: '0x123',
      },
    ];
  }
}
